baseURL: https://raddah.net
languageCode: ar-SA


# config.yaml
module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
    - disable: false


DefaultContentLanguage: ar

languages:
  ar:
    title: رَدَّه
    languagedirection: rtl
    languageName: العربية
    # title: مدونتي
    # contentDir: content/arabic
    weight: 1
    description:  مساحتي الخاصة حيث أدون ما أهتم وأرى | أسعى لترك أثر طيب
    sidebar:
    #Subtitle multiline 
      Subtitle: شغوف وطموح وأيضا مؤسس ومساهم لعدة مشاريع...

        اطْلُبِ العلمَ ولا تَكْسَلْ، فَمَا     أَبْعَدَ الخَيْر على أهْلِ الكَسَلْ
      avatar:
        local: true
        src: images/preview.jpg
      author:
      name: Raddah
    copyright: كافة الحقوق محفوظة
    languageCode: ar-sa
    menu:
      main:
        - identifier: home
          name: الرئيسية
          url: /
          weight: 1
          params:
            icon: home

        - identifier: projects
          name: مشاريعي
          url: /projects
          weight: 2
          params:
            icon: project

        - identifier: about
          name: عني
          url: /about
          weight: 3
          params:
            icon: user

        # - identifier: Archives
        #   name: الأرشيف
        #   url: /archives
        #   weight: 4
        #   params:
        #     icon: archives

        - identifier: search
          name: بحث
          url: /search
          weight: 5
          params:
            icon: search
      ### Social Media #####
      social:
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/iRaddah_
          weight: 1
          params:
            icon: brand-twitter

        - identifier: github
          name: GitHub
          url: https://github.com/Raddah
          weight: 2
          params:
            icon: brand-github
        
#        - identifier: gitlab
#          name: GitLab
#          url: https://gitlab.com/Raddah
#          weight: 3
#          params:
#            icon: brand-gitlab
      ### End of Social Media ####
################ ENGLSIH ######################
  en:
    title: Raddah
    languageName: English
    description: Personal blog!, I write about tech, infrastructure and the occasional personal opinion.
    sidebar:
      subtitle: Passionate,
        ambitious, and also a founder and contributor to several projects.
        Seek knowledge and do not be lazy, for goodness is never far from the diligent.
      avatar:
          local: true
          src: images/preview.jpg
    weight: 2
    author:
      name: Raddah
    copyright: All rights reserved
    languageCode: en-us
    menu:
      main:
        - identifier: home
          name: Home
          url: /en
          weight: 1
          params:
            icon: home

        - identifier: projects
          name: My Projects
          url: /en/projects
          weight: 2
          params:
            icon: project

        - identifier: about
          name: About
          url: /en/about
          weight: 3
          params:
            icon: user

        - identifier: search
          name: Search
          url: /en/search
          weight: 4
          params:
            icon: search

        # - identifier: archives
        #   name: Archives
        #   url: /en/archives
        #   weight: 5
        #   params:
        #     icon: archives

      social:
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/iRaddah_
          weight: 1
          params:
            icon: brand-twitter

        - identifier: github
          name: GitHub
          url: https://github.com/Raddah
          weight: 2
          params:
            icon: brand-github
########### END OF ENGLISH MENU ############


permalinks:
  post: /:slug/
  page: /:slug/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: favicon.ico

  footer:
#    since: 2023
    customText: RADDAH | رَدَّه

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: true
      # default: Licensed under CC BY-NC-SA 4.0

#   widgets:
#     homepage:
#       - type: search
#       - type: archives
#         params:
#           limit: 5
#       - type: categories
#         params:
#           limit: 10
#       - type: tag-cloud
#         params:
#           limit: 10
#     page:
#       - type: toc
#     opengraph:
#     twitter:
#       # Your Twitter username
#       site: Raddah

